version: '3.7'

# starts 1 docker containers running minio server instances.
# you can access
# it through port 9090.
# http://localhost:9090/minio/login
services:
  minio:
    image: minio/minio:RELEASE.2021-02-24T18-44-45Z
    volumes:
      - ./storage/data:/data
    ports:
      - "9090:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
